name: CI @ ubuntu-latest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Enable git longpaths
        run: git config --global core.longpaths true
      - name: Setup .NET Core SDK (v3.1.102)
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.102
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test --configuration Release --no-build
      - name: Nuget Build Number Generator
        uses: emrekas/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: Publish NuGet
        uses: rohith/publish-nuget@v2.0.0
        with:
          PROJECT_FILE_PATH: Source/Kf.Extensions.Microsoft.Hosting/Kf.Extensions.Microsoft.Hosting.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          TAG_FORMAT: v*-BUILD_NUMBER # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key